"""
Generates plain English answers from SQL results using Groq Llama 3 70B.
Falls back to OpenAI GPT-4o if Groq fails.
"""

import os
import sys
import pandas as pd

from groq import Groq
from openai import OpenAI

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from ml_pipeline.monitoring.logger import JSONLogger

logger = JSONLogger()

GROQ_EXPLAIN_MODEL = "llama-3.3-70b-versatile"
OPENAI_FALLBACK_MODEL = "gpt-4o"
MAX_ROWS_IN_PROMPT = 20


def _df_to_markdown(df: pd.DataFrame) -> str:
    if df is None or df.empty:
        return "(no results)"
    return df.head(MAX_ROWS_IN_PROMPT).to_markdown(index=False)


def explain(
    question: str,
    sql: str,
    result_df: pd.DataFrame,
) -> tuple[str, str, str | None]:
    """
    Generate a plain English explanation of query results.

    Returns:
        (answer, llm_used, fallback_reason)
        fallback_reason is None if Groq was used successfully.
    """
    from app.config import settings

    table_md = _df_to_markdown(result_df)

    system_prompt = (
        "You are a pharmaceutical data analyst. "
        "Answer the user's question based on the SQL query results below. "
        "Write in clear, direct prose. No bullet points unless listing items. "
        "Include one proactive insight beyond the literal answer. "
        "Keep it under 200 words."
    )

    user_message = (
        f"Question: {question}\n\n"
        f"SQL executed:\n{sql}\n\n"
        f"Results:\n{table_md}"
    )

    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_message},
    ]

    # Try Groq first
    try:
        client = Groq(api_key=settings.groq_api_key)
        response = client.chat.completions.create(
            model=GROQ_EXPLAIN_MODEL,
            messages=messages,
            temperature=0.3,
            max_tokens=512,
        )
        answer = response.choices[0].message.content.strip()
        logger.log("answer_generated", {"model": "groq"})
        return answer, "groq", None

    except Exception as groq_err:
        logger.log("fallback_triggered", {"reason": str(groq_err), "step": "explain"})

    # Fallback to OpenAI
    client = OpenAI(api_key=settings.openai_api_key)
    response = client.chat.completions.create(
        model=OPENAI_FALLBACK_MODEL,
        messages=messages,
        temperature=0.3,
        max_tokens=512,
    )
    answer = response.choices[0].message.content.strip()
    logger.log("answer_generated", {"model": "openai_fallback"})
    fallback_reason = "Groq was unavailable. This response was generated by OpenAI."
    return answer, "openai", fallback_reason
