"""
Validates DuckDB SQL queries generated by the LLM against the data registry schema
using sqlglot to prevent execution of queries with hallucinated tables or columns.
"""

from sqlglot import parse_one, exp
from sqlglot.errors import ParseError

from data_pipeline.registry import load_registry


def validate_sql(sql: str) -> list[str]:
    """
    Parses a SQL query and validates that all referenced tables and columns
    exist in the registry schema.
    
    Returns:
        A list of error strings. Empty list if the query is valid.
    """
    errors = []
    
    # 1. Parse the SQL to ensure it's syntactically valid DuckDB SQL
    try:
        ast = parse_one(sql, read="duckdb")
    except ParseError as e:
        return [f"SQL syntax error: {str(e)}"]

    # Load schema
    registry = load_registry()
    if not registry or "tables" not in registry:
        return ["Schema registry not found or empty."]

    # Create mapping of table -> [columns]
    schema = {t["name"]: set(t["columns"]) for t in registry["tables"]}
    
    # Track which tables the query is actually using
    tables_in_query = set()
    
    # 2. Extract and validate tables
    for table_node in ast.find_all(exp.Table):
        table_name = table_node.name
        # Ignore CTE aliases if we can
        if table_name not in schema:
            cte = table_node.parent
            while cte and not isinstance(cte, exp.CTE):
                cte = cte.parent
            if not cte:
               errors.append(f"Referenced table '{table_name}' does not exist in schema.")
        else:
            tables_in_query.add(table_name)

    # 3. Extract and validate columns
    # We must ensure that the column is valid specifically for the tables used in the query!
    for column_node in ast.find_all(exp.Column):
        col_name = column_node.name
        table_alias_or_name = column_node.table
        
        # Don't validate *
        if col_name == "*":
            continue
            
        col_found = False
        
        # If the query specifies the table (e.g., fact_rx.hcp_id)
        if table_alias_or_name and table_alias_or_name in schema:
            if col_name in schema[table_alias_or_name]:
                col_found = True
        else:
            # Table not specified or is an alias, search ONLY the base tables used in the query
            for t_name in tables_in_query:
                if col_name in schema[t_name]:
                    col_found = True
                    break
                         
        if not col_found:
            available_cols = []
            if tables_in_query:
                for t in tables_in_query:
                    available_cols.extend(list(schema[t]))
            else:
                 for cols in schema.values():
                     available_cols.extend(list(cols))
            
            hint = f" Available columns in the queried tables ({', '.join(tables_in_query) if tables_in_query else 'none'}): {', '.join(set(available_cols))}."
            errors.append(f"Referenced column '{col_name}' does not exist." + hint)

    # Deduplicate errors
    return list(dict.fromkeys(errors))
